import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Lab5Part4 extends JFrame {

    private CardLayout cardLayout;
    private JPanel cardPanel;

    public Lab5Part4() {
        // Create the frame
        setTitle("Favourites");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Initialize CardLayout and card panel
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);

        // Add panels to card layout
        cardPanel.add(createHolidayPanel(), "Holiday");
        cardPanel.add(createPastimePanel(), "Pastime");

        // Add card panel to frame
        add(cardPanel, BorderLayout.CENTER);

        // Create and add switch button
        JButton switchButton = new JButton("Switch Panel");
        switchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.next(cardPanel);
            }
        });
        add(switchButton, BorderLayout.SOUTH);

        // Create and set menu bar
        JMenuBar menuBar = new JMenuBar();
        JMenu viewMenu = new JMenu("View");
        JMenuItem switchMenuItem = new JMenuItem("Switch Panel");
        switchMenuItem.setAccelerator(KeyStroke.getKeyStroke("control S"));
        switchMenuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cardLayout.next(cardPanel);
            }
        });
        viewMenu.add(switchMenuItem);
        menuBar.add(viewMenu);
        setJMenuBar(menuBar);

        // Make the frame visible
        setVisible(true);
    }

    private JPanel createHolidayPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        JLabel titleLabel = new JLabel("The Birth of Venus by Alexandre Cabanel", JLabel.CENTER);
        titleLabel.setFont(new Font("Serif", Font.BOLD, 24));
        panel.add(titleLabel, BorderLayout.NORTH);

        // https://www.metmuseum.org/art/collection/search/435831
        JLabel imageLabel = new JLabel(new ImageIcon("img/Part4/The Birth of Venus - The Metropolitan Museum of Art.jpg")); // Official image from The Metropolitan Museum of Art
        panel.add(imageLabel, BorderLayout.CENTER);

        JTextArea descriptionArea = new JTextArea("The first version of Cabanel's Birth of Venus (Musée d'Orsay, Paris) created a sensation at the Salon of 1863, which was dubbed the \"Salon of the Venuses\" owing to the number of alluring nudes on view. The Salon picture was purchased by Napoleon III for his personal collection. In 1875, New Yorker John Wolfe commissioned the present, slightly smaller, replica from Cabanel. The composition embodies ideals of academic art: mythological subject, graceful modeling, silky brushwork, and perfected form. This style was perennially popular with collectors, even as it was challenged by artists seeking a more personal interpretation of truth to nature, such as Courbet.\n");
        descriptionArea.setLineWrap(true);
        descriptionArea.setWrapStyleWord(true);
        panel.add(new JScrollPane(descriptionArea), BorderLayout.SOUTH);

        return panel;
    }

    private JPanel createPastimePanel() {
        JPanel panel = new JPanel(new BorderLayout());
        JLabel titleLabel = new JLabel("The Birth of Venus by Sandro Botticelli", JLabel.CENTER);
        titleLabel.setFont(new Font("Serif", Font.BOLD, 24));
        panel.add(titleLabel, BorderLayout.NORTH);

        // https://artsandculture.google.com/asset/the-birth-of-venus-sandro-botticelli/MQEeq50LABEBVg?hl=en
        JLabel imageLabel = new JLabel(new ImageIcon("img/Part4/The Birth of Venus by Sandro Botticelli.png")); // Generated by AI, because the museum don't provide an open "sourced" image
        panel.add(imageLabel, BorderLayout.CENTER);

        JTextArea descriptionArea = new JTextArea("The painting was commissioned by Lorenzo di Pierfrancesco de’Medici, a cousin of Lorenzo the Magnificent. The theme was probably suggested by the humanist Poliziano. It depicts Venus born from the sea foam, blown by the west wind, Zephyr, and the nymph, Chloris, towards one of the Horai, who prepares to dress her with a flowered mantle.\n");
        descriptionArea.setLineWrap(true);
        descriptionArea.setWrapStyleWord(true);
        panel.add(new JScrollPane(descriptionArea), BorderLayout.SOUTH);

        return panel;
    }

    public static void main(String[] args) {
        // Create an instance of Lab5Part4 and run it on the Event Dispatch Thread
        SwingUtilities.invokeLater(() -> new Lab5Part4());
    }
}
